"""Initial SQLite migration

Revision ID: 4040160e3420
Revises: 
Create Date: 2025-08-26 16:40:47.710077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4040160e3420'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cut_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=False),
    sa.Column('timestamp_utc', sa.DateTime(), nullable=False),
    sa.Column('cut_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cut_events_id'), 'cut_events', ['id'], unique=False)
    op.create_index(op.f('ix_cut_events_machine_id'), 'cut_events', ['machine_id'], unique=False)
    op.create_table('historical_machine_data',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('machine_id', sa.String(), nullable=True),
    sa.Column('downtime_reason_name', sa.String(), nullable=True),
    sa.Column('end_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('productivity', sa.String(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('shift', sa.String(), nullable=True),
    sa.Column('day_of_week', sa.String(), nullable=True),
    sa.Column('utilisation_category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_machine_data_id'), 'historical_machine_data', ['id'], unique=False)
    op.create_index(op.f('ix_historical_machine_data_machine_id'), 'historical_machine_data', ['machine_id'], unique=False)
    op.create_table('maintenance_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logged_time', sa.DateTime(), nullable=True),
    sa.Column('resolved_time', sa.DateTime(), nullable=True),
    sa.Column('incident_category', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('fourjaw_downtime_id', sa.String(), nullable=True),
    sa.Column('machine_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_tickets_fourjaw_downtime_id'), 'maintenance_tickets', ['fourjaw_downtime_id'], unique=False)
    op.create_index(op.f('ix_maintenance_tickets_id'), 'maintenance_tickets', ['id'], unique=False)
    op.create_index(op.f('ix_maintenance_tickets_machine_id'), 'maintenance_tickets', ['machine_id'], unique=False)
    op.create_index(op.f('ix_maintenance_tickets_status'), 'maintenance_tickets', ['status'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('product_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_code'),
    sa.UniqueConstraint('product_name')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('repair_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_name', sa.String(), nullable=False),
    sa.Column('stock_code', sa.String(), nullable=True),
    sa.Column('current_stock', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_name'),
    sa.UniqueConstraint('stock_code')
    )
    op.create_index(op.f('ix_repair_components_id'), 'repair_components', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('onboarded', sa.Boolean(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('production_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('scrap_length', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_runs_id'), 'production_runs', ['id'], unique=False)
    op.create_index(op.f('ix_production_runs_machine_id'), 'production_runs', ['machine_id'], unique=False)
    op.create_table('ticket_components_used',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('quantity_used', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['repair_components.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['maintenance_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_components_used_id'), 'ticket_components_used', ['id'], unique=False)
    op.create_table('ticket_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('caption', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['maintenance_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_images_id'), 'ticket_images', ['id'], unique=False)
    op.create_table('ticket_work_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['maintenance_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_work_notes_id'), 'ticket_work_notes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_work_notes_id'), table_name='ticket_work_notes')
    op.drop_table('ticket_work_notes')
    op.drop_index(op.f('ix_ticket_images_id'), table_name='ticket_images')
    op.drop_table('ticket_images')
    op.drop_index(op.f('ix_ticket_components_used_id'), table_name='ticket_components_used')
    op.drop_table('ticket_components_used')
    op.drop_index(op.f('ix_production_runs_machine_id'), table_name='production_runs')
    op.drop_index(op.f('ix_production_runs_id'), table_name='production_runs')
    op.drop_table('production_runs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_repair_components_id'), table_name='repair_components')
    op.drop_table('repair_components')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_maintenance_tickets_status'), table_name='maintenance_tickets')
    op.drop_index(op.f('ix_maintenance_tickets_machine_id'), table_name='maintenance_tickets')
    op.drop_index(op.f('ix_maintenance_tickets_id'), table_name='maintenance_tickets')
    op.drop_index(op.f('ix_maintenance_tickets_fourjaw_downtime_id'), table_name='maintenance_tickets')
    op.drop_table('maintenance_tickets')
    op.drop_index(op.f('ix_historical_machine_data_machine_id'), table_name='historical_machine_data')
    op.drop_index(op.f('ix_historical_machine_data_id'), table_name='historical_machine_data')
    op.drop_table('historical_machine_data')
    op.drop_index(op.f('ix_cut_events_machine_id'), table_name='cut_events')
    op.drop_index(op.f('ix_cut_events_id'), table_name='cut_events')
    op.drop_table('cut_events')
    # ### end Alembic commands ###
